---
opentsdb:
  hostname: tsd-host
  image: kamir/opentsdb-docker:latest
  environment:
    - WAITSECS=30    
  ports:
    - 4242:4242
    - 60000:60000
    - 60010:60010
    - 60020:60020
    - 60030:60030
  volumes:  
    - "./data:/data/hbase"
